version: '2.1'
services:
     elasticsearch:
       image: elasticsearch:7.6.2
       container_name: elasticsearch
       networks:
           docker-elk:
       environment:
          - node.name=es01
          - cluster.name=es-docker-cluster
          - discovery.type=single-node
          - bootstrap.memory_lock=true
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
       ulimits:
           memlock:
               soft: -1
               hard: -1
           nofile:
               soft: 65536
               hard: 65536
     kibana:
       image: kibana:7.6.2
       container_name: kibana
       environment:
          - "ELASTICSEARCH_URL=http://elasticsearch:9200"
       networks:
          - docker-elk
       depends_on:
          - elasticsearch
       ports:
          - "5601:5601"

networks:
  docker-elk:
    driver: bridge
